apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw-py
  name: hw-py
  namespace: argocd
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: hw-py
  sessionAffinity: None
  type: LoadBalancer